# Site settings
title: cblp's place
email: cblp@cblp.su
description: null # > # this means to ignore newlines
  # cblp's place
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cblp.github.io" # the base hostname & protocol for your site
twitter_username: cblp_su
github_username:  cblp

# Build settings
markdown: kramdown
